### ISSUE TITLE
Conto 4.4 bzw. Contao Manager Kompatibilität

### ISSUE THREAD

**Issue by heimseiten** [netzmacht/contao-font-awesome-inserttag#1]
Hallo David,

wäre es möglich die tolle Erweiterung für den Contao Manager bzw. für Contao 4.4 zur Verfügung zu stellen?

Das wäre echt klasse!

Danke und liebe Grüße
Niels

**Comment by dmolineus** [comment]
Manuell installiert läuft die Erweiterung bereits unter Contao 4. Eine Bereitstellung über Packagist/Composer muss ich noch implementieren.

**Comment by dmolineus** [comment]
Inzwischen steht die erste 2.0 Beta-Version zur Verfügung, die für Contao 4.4 (only) geeignet ist.

**Comment by designpilot** [comment]
Ich habe hier eine frische Contao 4.4.11 Installation, aber netzmacht/contao-font-awesome-inserttag lässt sich noch immer nicht über den Contao Manager (der ist inzwischen auch auf Beta 13) installieren.

Siehst Du da schon einen ungefähren Zeitplan ab wann es über den Contao Manager installierbar sein wird ???

**Comment by dmolineus** [comment]
Die Erweiterung steht ja bereits für den CM zur Verfügung. allerdings musste bisher explizit die Beta Version geladen werden ("~2.0@beta"). Ab sofort gibt es aber auch ein stabiles Release.
