### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by operatorone** [netzmacht/contao-font-awesome-inserttag#4]
Using the string "composer require netzmacht/contao-font-awesome-inserttag" brings up the following message:

```
[InvalidArgumentException]                                                                                                                                               
  Could not find package netzmacht/contao-font-awesome-inserttag at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

**Comment by dmolineus** [comment]
At the moment there is only a beta version for C4. So you have to decrease your minimum stability setting or force the beta.

`composer require netzmacht/contao-font-awesome-inserttag:2.0@beta`

**Comment by operatorone** [comment]
Thanks. I tried your string, but didn't work. I got this message 

> Problem 1
    - The requested package netzmacht/contao-font-awesome-inserttag 2.0@beta exists as netzmacht/contao-font-awesome-inserttag[2.0.0-beta1, 2.0.0-beta2, dev-develop, 2.1.x-dev] but these are rejected by your constraint.

and used this string 

> composer require netzmacht/contao-font-awesome-inserttag:2.0.0-beta2

This one worked :-)

**Comment by dmolineus** [comment]
Sorry forgot the "~" operator. Without your have to define an exact version. Following should work

`composer require netzmacht/contao-font-awesome-inserttag:~2.0@beta`
