### ISSUE TITLE
Verwendung mit Font Awesome 5

### ISSUE THREAD

**Issue by Schmidty2** [netzmacht/contao-font-awesome-inserttag#6]
Hallo, ich verwende Font Awesome 5 (als CSS eingebunden) und möchte im TinyMCE Inserttags verwenden.

Wenn man den Inserttag `{{fa::coffee 2x}}` verwendet, wird das Ganze im Quelltext umgesetzt in `<i class="fa fa-coffee fa-2x" aria-hidden="true">::before</i>` und das Symbol wird wie gewünscht dargestellt. Normalerweise müsste bei Font Awesome 5 hier aber `<i class="fas fa-coffee...` ausgegeben werden, aber durch die Rückwärtskompatibilität wird da ganze vermutlich richtig dargestellt.

Wenn man den Inserttag `{{fa::contao 2x}}` verwendet, wird das Ganze im Quelltext umgesetzt in `<i class="fa fa-contao fa-2x" aria-hidden="true">::before</i>` und das Symbol wird **nicht** dargestellt. Hier müsste im Quelltext `<i class=“fab fa-contao...` stehen.

Font Awesome verwendet ja in der Version 5 die Tags **fas-** / **fab-** / **far-** und in der Pro-Version noch **fal-** um Symbole einzufügen. Was muss ich in der parametes.yml eintragen, dass alle Tags der Version 5 unterstützt werden und wie müssen dann die dazugehörigen Inserttags aussehen?
Ich habe in der parameters.yml schon mit dem Eintrag `font_awesome_inserttag.icon_template: '<i class="%%s" aria-hidden="true"></i>'` experimentiert, bin aber nicht weiter gekommen.

Eintrag im TinyMCE
![inserttags im tinymce](https://user-images.githubusercontent.com/2067428/34909807-7030e9ea-f8a8-11e7-85ae-8538f952c4cf.JPG)

Ausgabe im Frontend
![inserttags_ausgabe](https://user-images.githubusercontent.com/2067428/34909808-7046cd46-f8a8-11e7-9d29-e678e7923135.JPG)

Quellcode
![inserttags_quelltext](https://user-images.githubusercontent.com/2067428/34909809-705e441c-f8a8-11e7-8709-f5067f0769cb.JPG)

**Comment by dmolineus** [comment]
Der bisherige FA 5 Support sieht vor, dass man explizit den Style ausgibt. Die neu hinzugekommenen Insert-Tags sind nun:

```
{{fas::coffee 2x}}
{{fal::coffee 2x}}
{{far::coffee 2x}}
{{fab::contao}}
```

Es ist aber eine sinnvolle Verbesserung, das Verhalten des fa-Tags konfigurierbar zu machen, sodass man es auf einen der Stile mappen kann für eine bessere Rückwärts-Kompatibilität. 

Ein standardmäßiges Mappen von `fa` auf `fas` halte ich nicht für sinnvoll, da noch FA 4 und FA 5 unterstützt werden soll. Außerdem mit Verwendung von JS auch FA eine Rückwärtskompatibiltitäts-Layer anbietet.

**Comment by Schmidty2** [comment]
Wenn man im tinyMCE folgende Eingabe macht, wird im Frontend nichts ausgegeben:
![inserttags im tinymce2](https://user-images.githubusercontent.com/2067428/34940884-a19e4b5e-f9f1-11e7-8dcd-ad7de4195ff8.JPG)

Der Grund ist, dass das **s** bzw. **b** an allen Tags mit ausgegeben wird und nicht nur beim ersten, einleitenden Tag. Wenn man in der Browservorschau die markierten Elemente entfernt, wird das Ganze richtig ausgegeben.
![inserttags_quelltext2](https://user-images.githubusercontent.com/2067428/34940885-a1b42104-f9f1-11e7-9621-d0bd10d04a0c.JPG)

In der parameters.yml habe ich derzeit keinen Eintrag, muss hier ein Eintrag hinzugefügt werden damit das Ganze funktioniert?

**Comment by dmolineus** [comment]
Das ist noch ein Fehler. Behebe ich im nächsten Release.

**Comment by dmolineus** [comment]
Ist nun gefixt. Außerdem wurde mit `default_style` eine Option hinzugefügt, sodass der `fa` Tag individuell auf einen Stil konfiguriert werden kann für den FA 5 Support.

**Comment by Schmidty2** [comment]
funktioniert jetzt wie gewünscht - Danke.
