### ISSUE TITLE
Contao 4.6 Kompatibilität

### ISSUE THREAD

**Issue by heimseiten** [netzmacht/contao-font-awesome-inserttag#7]
Hallo David,

ist geplant die Erweiterung mit Contao 4.6 kompatibel zu machen?

Danke und liebe Grüße
Niels

**Comment by heimseiten** [comment]
Hallo David,

entschuldige, der Fehler lag scheinbar doch woanders. Beim nächsten mal probiere ich mehr aus bevor ich ein Issues aufmache ;).

Danke und liebe Grüße
Niels

**Comment by dmolineus** [comment]
Mir ist keine mögliche Ursache für ein Fehler bekannt.
