### ISSUE TITLE
Fehlermeldung bei Update auf Contao 4.11

### ISSUE THREAD

**Issue by seibtph** [netzmacht/contao-font-awesome-inserttag#9]
Beim Update des NATURE Theme (die eure Erweiterung als Abhängigkeit hat) auf Contao 4.11 bekam ich folgende Fehlermeldung:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in C:\laragon\www\nature49\vendor\netzmacht\contao-font-awesome-inserttag\src\DependencyInjection\Configuration.php on line 44 and at least 1 expected in C:\laragon\www\nature49\vendor\symfony\config\Definition\Builder\TreeBuilder.php:26
Stack trace:
#0 C:\laragon\www\nature49\vendor\netzmacht\contao-font-awesome-inserttag\src\DependencyInjection\Configuration.php(44): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 C:\laragon\www\nature49\vendor\symfony\config\Definition\Processor.php(50): Netzmacht\Contao\FontAwesomeInsertTag\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 C:\laragon\www\nature49\vendor\symfony\dependency-injection\Extension\Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Netzmacht\Contao\FontAwesomeInsertTag\DependencyInjection\Configuration), Array)
#3 C:\laragon\www in C:\laragon\www\nature49\vendor\symfony\config\Definition\Builder\TreeBuilder.php on line 26
```

Durch Anpassung der Funktion in der Configuration.php konnte ich den Fehler lösen:

```
$treeBuilder = new TreeBuilder('netzmacht_font_awesome_insert_tag');

$treeBuilder
    ->getRootNode()
    ->children()
        ->scalarNode('icon_template')
        ->end()
        ->scalarNode('stack_template')
        ->end()
        ->scalarNode('default_style')
        ->defaultValue('fa')
        ->end()
        ->end();

return $treeBuilder;
```

Habt ihr die Erweiterung schonmal für Contao 4.11 getestet? Diese erscheint ja am Montag.

**Comment by dmolineus** [comment]
Die Erweiterung ist derzeit nicht kompatibel mit `symfony/config ^5.0`. Da leider keine Abhängigkeiten definiert sind, kommt es zu dem Fehler. PRs sind willkommen.

**Comment by seibtph** [comment]
Ok, ich habe da mal einen Pull Request angelegt.

**Comment by think-digital-agency** [comment]
Ist der Fehler durch den PR behoben? Ich erhalte gerade bei einigen Themes dasselbe Problem mit Contao 4.11-ern. Danke für eure Bemühungen 👍

**Comment by seibtph** [comment]
Für Contao 4.11 zumindest ging es, aber das verursacht noch Probleme mit Contao 4.4. Man kann aber in der composer.json folgende Zeile unter require hinzufügen, dann sollte es auch klappen: `"symfony/config": "4.4.*"`

**Comment by dmolineus** [comment]
Release 2.1.1 is Contao 4.9 compatible only and includes the fix, see https://github.com/netzmacht/contao-font-awesome-inserttag/compare/2.0.1...2.1.1
